Repository exercism/rust, pull requests merged in 2023-07, with the labels that each got.

#1705 Convert `average_run_time` to an integer
  config.json
Labels: x:size/tiny

#1706 Fix typo
  exercises/practice/doubly-linked-list/src/pre_implemented.rs
Labels: x:size/tiny

#1708 Fix new clippy warnings
  exercises/practice/paasio/tests/paasio.rs
  exercises/practice/proverb/tests/proverb.rs
Labels: x:rep/small

#1709 Remove impls of deprecated exercises
  exercises/practice/hexadecimal/src/lib.rs
  exercises/practice/nucleotide-codons/src/lib.rs
Labels: x:rep/tiny

#1707 Clarify reason for disabled lint
  exercises/practice/binary-search/tests/binary-search.rs
Labels: x:size/tiny

#1710 Improve instructions of 'forth'
  exercises/practice/forth/.docs/instructions.append.md
Labels: x:rep/small
